/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardEndExerciseRouteImport } from './routes/_dashboard/endExercise'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSplatRouteImport } from './routes/_public/$'
import { Route as PublicFaqRouteImport } from './routes/_public/faq'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as DashboardDatabaseAnswersRouteImport } from './routes/_dashboard/database/answers'
import { Route as DashboardDatabaseUsersRouteImport } from './routes/_dashboard/database/users'
import { Route as DashboardExerciseIndexRouteImport } from './routes/_dashboard/exercise/index'
import { Route as DashboardExerciseTopicIdRouteImport } from './routes/_dashboard/exercise/$topicId'
import { Route as DashboardMyAnswersTopicIdRouteImport } from './routes/_dashboard/myAnswers/$topicId'
import { Route as DashboardStudentsAnswersTopicIdRouteImport } from './routes/_dashboard/studentsAnswers/$topicId'
import { Route as DashboardTopicsIndexRouteImport } from './routes/_dashboard/topics/index'
import { Route as DashboardTopicsListTopicIdRouteImport } from './routes/_dashboard/topics/list/$topicId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEndExerciseRoute = DashboardEndExerciseRouteImport.update({
  id: '/endExercise',
  path: '/endExercise',
  getParentRoute: () => DashboardRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSplatRoute = PublicSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardDatabaseAnswersRoute =
  DashboardDatabaseAnswersRouteImport.update({
    id: '/database/answers',
    path: '/database/answers',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDatabaseUsersRoute = DashboardDatabaseUsersRouteImport.update({
  id: '/database/users',
  path: '/database/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExerciseIndexRoute = DashboardExerciseIndexRouteImport.update({
  id: '/exercise/',
  path: '/exercise/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExerciseTopicIdRoute =
  DashboardExerciseTopicIdRouteImport.update({
    id: '/exercise/$topicId',
    path: '/exercise/$topicId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMyAnswersTopicIdRoute =
  DashboardMyAnswersTopicIdRouteImport.update({
    id: '/myAnswers/$topicId',
    path: '/myAnswers/$topicId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentsAnswersTopicIdRoute =
  DashboardStudentsAnswersTopicIdRouteImport.update({
    id: '/studentsAnswers/$topicId',
    path: '/studentsAnswers/$topicId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTopicsIndexRoute = DashboardTopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTopicsListTopicIdRoute =
  DashboardTopicsListTopicIdRouteImport.update({
    id: '/topics/list/$topicId',
    path: '/topics/list/$topicId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/endExercise': typeof DashboardEndExerciseRoute
  '/$': typeof PublicSplatRoute
  '/faq': typeof PublicFaqRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/database/answers': typeof DashboardDatabaseAnswersRoute
  '/database/users': typeof DashboardDatabaseUsersRoute
  '/exercise/$topicId': typeof DashboardExerciseTopicIdRoute
  '/myAnswers/$topicId': typeof DashboardMyAnswersTopicIdRoute
  '/studentsAnswers/$topicId': typeof DashboardStudentsAnswersTopicIdRoute
  '/exercise/': typeof DashboardExerciseIndexRoute
  '/topics/': typeof DashboardTopicsIndexRoute
  '/topics/list/$topicId': typeof DashboardTopicsListTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/endExercise': typeof DashboardEndExerciseRoute
  '/$': typeof PublicSplatRoute
  '/faq': typeof PublicFaqRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/database/answers': typeof DashboardDatabaseAnswersRoute
  '/database/users': typeof DashboardDatabaseUsersRoute
  '/exercise/$topicId': typeof DashboardExerciseTopicIdRoute
  '/myAnswers/$topicId': typeof DashboardMyAnswersTopicIdRoute
  '/studentsAnswers/$topicId': typeof DashboardStudentsAnswersTopicIdRoute
  '/exercise': typeof DashboardExerciseIndexRoute
  '/topics': typeof DashboardTopicsIndexRoute
  '/topics/list/$topicId': typeof DashboardTopicsListTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/endExercise': typeof DashboardEndExerciseRoute
  '/_public/$': typeof PublicSplatRoute
  '/_public/faq': typeof PublicFaqRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/': typeof PublicIndexRoute
  '/_dashboard/database/answers': typeof DashboardDatabaseAnswersRoute
  '/_dashboard/database/users': typeof DashboardDatabaseUsersRoute
  '/_dashboard/exercise/$topicId': typeof DashboardExerciseTopicIdRoute
  '/_dashboard/myAnswers/$topicId': typeof DashboardMyAnswersTopicIdRoute
  '/_dashboard/studentsAnswers/$topicId': typeof DashboardStudentsAnswersTopicIdRoute
  '/_dashboard/exercise/': typeof DashboardExerciseIndexRoute
  '/_dashboard/topics/': typeof DashboardTopicsIndexRoute
  '/_dashboard/topics/list/$topicId': typeof DashboardTopicsListTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/endExercise'
    | '/$'
    | '/faq'
    | '/login'
    | '/register'
    | '/database/answers'
    | '/database/users'
    | '/exercise/$topicId'
    | '/myAnswers/$topicId'
    | '/studentsAnswers/$topicId'
    | '/exercise/'
    | '/topics/'
    | '/topics/list/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/endExercise'
    | '/$'
    | '/faq'
    | '/login'
    | '/register'
    | '/database/answers'
    | '/database/users'
    | '/exercise/$topicId'
    | '/myAnswers/$topicId'
    | '/studentsAnswers/$topicId'
    | '/exercise'
    | '/topics'
    | '/topics/list/$topicId'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_public'
    | '/_dashboard/dashboard'
    | '/_dashboard/endExercise'
    | '/_public/$'
    | '/_public/faq'
    | '/_public/login'
    | '/_public/register'
    | '/_public/'
    | '/_dashboard/database/answers'
    | '/_dashboard/database/users'
    | '/_dashboard/exercise/$topicId'
    | '/_dashboard/myAnswers/$topicId'
    | '/_dashboard/studentsAnswers/$topicId'
    | '/_dashboard/exercise/'
    | '/_dashboard/topics/'
    | '/_dashboard/topics/list/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/endExercise': {
      id: '/_dashboard/endExercise'
      path: '/endExercise'
      fullPath: '/endExercise'
      preLoaderRoute: typeof DashboardEndExerciseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/$': {
      id: '/_public/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof PublicSplatRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_dashboard/database/answers': {
      id: '/_dashboard/database/answers'
      path: '/database/answers'
      fullPath: '/database/answers'
      preLoaderRoute: typeof DashboardDatabaseAnswersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/database/users': {
      id: '/_dashboard/database/users'
      path: '/database/users'
      fullPath: '/database/users'
      preLoaderRoute: typeof DashboardDatabaseUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/exercise/': {
      id: '/_dashboard/exercise/'
      path: '/exercise'
      fullPath: '/exercise/'
      preLoaderRoute: typeof DashboardExerciseIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/exercise/$topicId': {
      id: '/_dashboard/exercise/$topicId'
      path: '/exercise/$topicId'
      fullPath: '/exercise/$topicId'
      preLoaderRoute: typeof DashboardExerciseTopicIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/myAnswers/$topicId': {
      id: '/_dashboard/myAnswers/$topicId'
      path: '/myAnswers/$topicId'
      fullPath: '/myAnswers/$topicId'
      preLoaderRoute: typeof DashboardMyAnswersTopicIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/studentsAnswers/$topicId': {
      id: '/_dashboard/studentsAnswers/$topicId'
      path: '/studentsAnswers/$topicId'
      fullPath: '/studentsAnswers/$topicId'
      preLoaderRoute: typeof DashboardStudentsAnswersTopicIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/topics/': {
      id: '/_dashboard/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof DashboardTopicsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/topics/list/$topicId': {
      id: '/_dashboard/topics/list/$topicId'
      path: '/topics/list/$topicId'
      fullPath: '/topics/list/$topicId'
      preLoaderRoute: typeof DashboardTopicsListTopicIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardEndExerciseRoute: typeof DashboardEndExerciseRoute
  DashboardDatabaseAnswersRoute: typeof DashboardDatabaseAnswersRoute
  DashboardDatabaseUsersRoute: typeof DashboardDatabaseUsersRoute
  DashboardExerciseTopicIdRoute: typeof DashboardExerciseTopicIdRoute
  DashboardMyAnswersTopicIdRoute: typeof DashboardMyAnswersTopicIdRoute
  DashboardStudentsAnswersTopicIdRoute: typeof DashboardStudentsAnswersTopicIdRoute
  DashboardExerciseIndexRoute: typeof DashboardExerciseIndexRoute
  DashboardTopicsIndexRoute: typeof DashboardTopicsIndexRoute
  DashboardTopicsListTopicIdRoute: typeof DashboardTopicsListTopicIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardEndExerciseRoute: DashboardEndExerciseRoute,
  DashboardDatabaseAnswersRoute: DashboardDatabaseAnswersRoute,
  DashboardDatabaseUsersRoute: DashboardDatabaseUsersRoute,
  DashboardExerciseTopicIdRoute: DashboardExerciseTopicIdRoute,
  DashboardMyAnswersTopicIdRoute: DashboardMyAnswersTopicIdRoute,
  DashboardStudentsAnswersTopicIdRoute: DashboardStudentsAnswersTopicIdRoute,
  DashboardExerciseIndexRoute: DashboardExerciseIndexRoute,
  DashboardTopicsIndexRoute: DashboardTopicsIndexRoute,
  DashboardTopicsListTopicIdRoute: DashboardTopicsListTopicIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PublicRouteChildren {
  PublicSplatRoute: typeof PublicSplatRoute
  PublicFaqRoute: typeof PublicFaqRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicSplatRoute: PublicSplatRoute,
  PublicFaqRoute: PublicFaqRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
